### ISSUE TITLE
Timeout for location resolution

### ISSUE THREAD

**Issue by sellnat77** [Mosquito-Mashers/Decisionator#29]
Need to implement a feature to fire a timeout event when we cant resolve location after say...30 seconds? This is up for grabs if anyone wants it
@Ronald-N 
@jtjr 
@JohnCover

**Comment by Ronald-N** [comment]
John or Jose if you beat me to this, we should apply this timeout to the event refresh as well

**Comment by JohnCover** [comment]
I moved this to locationUpdate_OnUserLogin#46 - this branch outdated and no need to push to master.
