### ISSUE TITLE
Invite list show user info

### ISSUE THREAD

**Issue by sellnat77** [Mosquito-Mashers/Decisionator#45]
We need to figure out what we want to show in the invite list
ie show who is the host, show who hasnt rsvp'ed yet, show who has rsvp'ed

@jtjr @JohnCover @Ronald-N
Also, when deciding the final location, should we only decide based on who has rsvp'ed or base it one everyone invited?

**Comment by JohnCover** [comment]
I would say determine based on everyone invited before RSVP.  The idea being the determined location should increase RSVPs.
